export { default as Header } from './Header'
export { default as Main } from './Main'
export { default as Earth } from './Earth'
export { default as Moon } from './Moon'
export { default as Loader } from './Loader'
